### ISSUE TITLE
jsonschema bug for vis

### ISSUE THREAD

**Issue by sm11197** [julianmichael/debate#100]
Need to downgrade to jsonschema version < 4 for Altair 4

I got this error when trying to use the bin argument in bar charts:
...
```
debate/.venv/lib/python3.10/site-packages/jsonschema/validators.py", line 101, in _id_of
    return schema.get("$id", "")
AttributeError: 'list' object has no attribute 'get'
```

Found the solution of downgrading[ here](https://github.com/altair-viz/altair/issues/2707)
Ran ` pip install --force-reinstall -v "jsonschema<4"` and now code works

But I'm not sure how/if we should do this universally

**Comment by julianmichael** [comment]
If you find the exact jsonschema version we want (say it’s 3.9.9 or something), you can add it as a line to requirements.txt like

jsonschema==3.9.9

and it should work for people upon normal install.

**Comment by sm11197** [comment]
That command resulted in `installed attrs-22.2.0 jsonschema-3.2.0 pyrsistent-0.19.3 setuptools-67.6.1 six-1.16.0`
I can add those to requirements.txt

**Comment by julianmichael** [comment]
No, you don’t need to. Having it in requirements.txt is much like handing it to pip install — it’ll take care of those dependencies. Just jsonschema should work.
