### ISSUE TITLE
"Undo" functionality

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#12]
Sending a message by mistake can be a pretty big goof since we enforce turn order and message limits, so we should let people undo.

In theory you might want a time limit on this or something, but we're working with trusted debaters so I wouldn't worry about abuse. It should be pretty easy to add an undo button which is only active when yours was the last turn.

**Comment by idavidrein** [comment]
Will attempt to do this, but may stop if it's taking me too long to get up-to-speed on scala and js

**Comment by idavidrein** [comment]
Okay I think it'll take me too much time to get up to speed with scala and general web development for this to feel worth it.

**Comment by smithjessk** [comment]
Working on this

**Comment by smithjessk** [comment]
@julianmichael Should the undo button populate the textarea with the last message that was sent?

**Comment by smithjessk** [comment]
@julianmichael should we make a separate todo for an optional timeout on how long people can press this button?

**Comment by smithjessk** [comment]
and should it be different for official and practice debates?

**Comment by smithjessk** [comment]
perhaps we want to allow arbitrary undos (by the moderator?)

**Comment by julianmichael** [comment]
Agree on populating with the message that got undone and having the timers. Official and practice debate distinction is more for record-keeping purposes and I think debate operations should be the same.
