### ISSUE TITLE
Better debate metadata in lobby

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#26]
- [x] squarer shape & flexbox rows
- [x] 'pending' / 'waiting to begin' status for debates that haven't really started yet, ie, are set up but no speech has been submitted
- [x] whose turn it is (& whether it's yours, ie, shown by bolding/styling or something)
- [x] role assignments (again with styling done accordingly for judge and debaters)
- [x] story title
- [x] honest/dishonest won / by how much (perhaps represent with green/red color intensity)
- [x] Better sorting/organizing (headings for each debate status — in progress, pending, complete — and correctly sorting by recency under each heading, which it seems not to do right now. I think my current sorting is broken)

**Comment by smithjessk** [comment]
1efee35 @julianmichael I think changing [`getRoomList`](https://github.com/julianmichael/debate/commit/1efee35a1e9874ed4e2c4c65f01b3844699f45af#diff-f6b811de7d54d1de84836057abd90635d28612e25cb6722e5c030fedbf50cc07R82) as such fixes the last bullet. But I'm not sure if there's any _subtle_ ways in which changing the sorting order of `getRoomList` messes anything up.

**Comment by julianmichael** [comment]
That seems right to me. Actually, especially if we're going to be partitioning out the rooms into sections anyway in the UI, I think it's probably nicest to put the latest timestamp value in the room metadata, send all of the metadata to the client as a set, and have the client do the sorting/organizing logic in the view. I think I might have had it this way with the idea of avoiding superfluous updates to the lobby data... but in retrospect, that seems like premature optimization.

**Comment by smithjessk** [comment]
@julianmichael 

> are set up but no speech has been submitted

Just TBC- if a judge has submitted an initial judgement, then it'll be marked `InProgress` not `WaitingToBegin`. Sounds good?

**Comment by julianmichael** [comment]
Yep!

**Comment by julianmichael** [comment]
Finished above.

**Comment by julianmichael** [comment]
(With bonus stuff too, like restyling as bootstrap cards, relative timestamps, improving the search/filtering, etc.)
