### ISSUE TITLE
Defaults for --port and --save?

### ISSUE THREAD

**Issue by smithjessk** [julianmichael/debate#36]
What about adding defaults `8080` and `save/` for` --port` and `--save` respectively? So that we don't have to type them every time.

**Comment by julianmichael** [comment]
Totally fine, I usually just arrow up to previous terminal command but no
harm to add defaults.

For minor things like this which seem obvious, feel free to just go ahead
and do it, no need for the extra friction of opening issues (though I
certainly won't deny you the satisfaction of closing them). I'll follow the
commits and, worst case, change it back ;)
