### ISSUE TITLE
Hierarchical lobby tabs (formerly 'reword lobby panes')

### ISSUE THREAD

**Issue by smithjessk** [julianmichael/debate#37]
E.g., making 'All Official Debates' match with 'Practice Debates'. (Like 'All Practice Debates')

**Comment by julianmichael** [comment]
How about just changing "All Official Debates" to "Official Debates," and then adding practice debates (to which the current user is assigned) to the My Debates tab under a separate (lower) heading?

**Comment by julianmichael** [comment]
New plan: hierarchical tabs
* Debates
  * My Debates
  * Official Debates
  * Practice Debates
* Leaderboard
  * Judge
  * Honest Debater
  * Dishonest Debater
* Admin
  * Create Debates
  * Auto-Schedule / Story Catalog (etc.)

The sorting strategy can persist between sub-leaderboards so you can easily switch tabs and compare tables / see how the order changes.

**Comment by julianmichael** [comment]
Finished in 24eac67.
