### ISSUE TITLE
Button to join a room doesn't turn the mouse icon into a clicker finger

### ISSUE THREAD

**Issue by smithjessk** [julianmichael/debate#38]
Hovering over the button to join a room doesn't change my mouse to a click icon, which threw me a bit. 

<img width="880" alt="image" src="https://user-images.githubusercontent.com/5957838/205763196-ea1f1a90-f02f-46f6-88a7-53446ffb7ee4.png">

(Maybe this is because I messed with the `adminOnly` style, @julianmichael?)

**Comment by julianmichael** [comment]
It should dim the button a bit, or it may happen when the button is disabled. But this seems like an issue with bootstrap styling? Not sure why it wouldn't change to a pointer finger thing. Worth making sure this is fixed for all buttons.
