### ISSUE TITLE
When clicked, undo button should populate textarea with last response

### ISSUE THREAD

**Issue by smithjessk** [julianmichael/debate#43]
Key feature is converting `Vector[SpeechSegment]` to a string and then doing `currentMessage.setState` in `DebatePanel.scala`.

**Comment by smithjessk** [comment]
From @julianmichael: 

I think it should be pretty simple, looks something like
```
def speechSegmentsToString(segs: Vector[SpeechSegment]) = segs.foldMap {
  case SpeechSegment.Text(text) => text
  case SpeechSegment.Quote(span) => span2text(span)
}
```
though can factor that into a toText method on SpeechSegment

**Comment by julianmichael** [comment]
Finished as of b6e312eb30f07c8382de7fae38c61c9c38bce579.

After refactoring stuff into an explicit state transitions object, it was straightforward to add the undone message's info into the 'undo' transition.
