### ISSUE TITLE
Use lenses in undo buttons

### ISSUE THREAD

**Issue by smithjessk** [julianmichael/debate#44]
Per [this comment](https://github.com/julianmichael/debate/pull/42#pullrequestreview-1210549241), make `DebatePanel.scala`'s undo buttons uses lenses for cleaner code

**Comment by julianmichael** [comment]
Thought about it a bit more and I have another idea which I think should be cleaner, I’ll look into it at some point

**Comment by julianmichael** [comment]
Finished as of b6e312eb30f07c8382de7fae38c61c9c38bce579.

Didn't actually use lenses/optics — I produced objects explicitly corresponding to the state transitions available at the current debate state.
