### ISSUE TITLE
Better timestamps

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#5]
Probably we want actual times listed after each argument instead of just deltas. Or maybe both; and could be displayed better (more like typical text messages do it maybe).

**Comment by smithjessk** [comment]
I think this is done.  (And there's an improvement here: https://github.com/julianmichael/debate/pull/16)

**Comment by julianmichael** [comment]
Will look at fixing conflicts to merge the PR

**Comment by smithjessk** [comment]
Ty!

**Comment by julianmichael** [comment]
Oops, forgot to close since I pushed the fix separately
