### ISSUE TITLE
Streamline the build for prod/deployment

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#60]
See #54. I want a setup where we can start the server at a single endpoint for production. This makes it easier to set it up behind a reverse proxy.

**Comment by julianmichael** [comment]
@UFO-101 I am trying the loop you suggested in the readme, and I'm not sure if it saves time. On my Macbook Air (M2), it takes about 10s to do an incremental recompile/re-link after changing one of the JS files, both in the new configuration and in the old one. (i.e., running `mill debate.js.fastestOpt` after changing one of the scalajs files in 9a3708fc54e306854fdb4ee7c047d87294e6be03). Do you notice a difference between the reload times in the two configs?

You mentioned in the PR that you found the new build easier to work with — are there other advantages that we get from it besides speed? In the old build we can also just incrementally recompile/re-link the JS and leave the server running if we want. If the only advantage is using NPM, then we can use mill-bundler instead, like I was trying here (05d4b11df89f640c1b6137be421d9c2428e5464d). And requiring the server to restart also gives us a way of knowing when the page is updated without having to look at the terminal (the overhead over compilation from re-running the program seems minimal).

I'm thinking of maybe moving to mill-bundler anyway unless there's a clear advantage to using vite. I really like having the build set up so that I can just tell it to start at a desired port and not worry about it. That makes deployment super simple.

**Comment by julianmichael** [comment]
Ah I see now that it's automatically refreshing the page when it updates — that's nice. Not sure if it did that before.

**Comment by UFO-101** [comment]
> On my Macbook Air (M2), it takes about 10s to do an incremental recompile/re-link after changing one of the JS files, both in the new configuration and in the old one. Do you notice a difference between the reload times in the two configs?

Uh oh - I think I've been silly 🤦. I think when I first started I was blindly following [the command in the README](https://github.com/julianmichael/debate/blob/dd20567e51867dd9fe95ecd110ea21a2bad221bc/README.md), which was `mill -i debate.dev.serve --port 8080 --save save`. So I think I wasn't using incremental builds, which could explain why it was so slow. [This conversation](https://cilvr.slack.com/archives/C049W42LER0/p1670600710812569) makes me suspect that Jess may have been doing the same.

> You mentioned in the PR that you found the new build easier to work with — are there other advantages that we get from it besides speed?

Well I think the updated `build.sc` is easier to understand (eg. no build scripts) but maybe that's just cause I'm not used to `mill` but I am used to `npm`.

Besides that, using vite for our production build allows us to use [rollup](https://rollupjs.org/guide/en/) plugins. The one that I always use is [autoprefixer](https://github.com/postcss/autoprefixer) which automatically makes your CSS cross-browser compatible. In practice this may not be super important though.

> Ah I see now that it's automatically refreshing the page when it updates

So vite should allow us to have **hot module reloading, which I think will be the main benefit compared to the old build**. It isn't working yet though.

> I'm thinking of maybe moving to mill-bundler anyway unless there's a clear advantage to using vite. I really like having the build set up so that I can just tell it to start at a desired port and not worry about it. That makes deployment super simple.

That's fair. I think I should be able to get it working from a single port with vite.

**Comment by UFO-101** [comment]
RE: [Return to some of the old build structure](https://github.com/julianmichael/debate/commit/3137cdac1eec99f405ecfd8787e1e9cab9400be3#diff-c6f64a5895d9f518051cf83f8557f492ec6f5683a34c2914a46a894001e62726)

<img width="403" alt="Screen Shot 2022-12-25 at 02 59 16" src="https://user-images.githubusercontent.com/47218308/209455693-24eac088-b708-453c-b0b5-7aefa85ee39f.png">

IntelliJ does not like this structure 😢 
There probably is a workaround though...

**Comment by julianmichael** [comment]
@UFO-101 sorry for the delay —

> I was blindly following [the command in the README](https://github.com/julianmichael/debate/blob/dd20567e51867dd9fe95ecd110ea21a2bad221bc/README.md), which was `mill -i debate.dev.serve --port 8080 --save save`. So I wasn't using incremental builds, which could explain why it was so slow.

I think that should do incremental recompiles but issue is that re-linking isn't incremental.

> Well I think the updated build.sc is easier to understand (eg. no build scripts) but maybe that's just cause I'm not used to mill but I am used to npm.
> 
> Besides that, using vite for our production build allows us to use [rollup](https://rollupjs.org/guide/en/) plugins. The one that I always use is [autoprefixer](https://github.com/postcss/autoprefixer) which automatically makes your CSS cross-browser compatible. In practice this may not be super important though.

Ah, cross-browser compatibility is one of the things scalacss gives us. And, I think we should also be able to use rollup plugins with mill-bundler as long as we're using the rollup linker. It might require futzing with the mill-bundler code a bit though. And yeah I think it might be a familiarity thing, because I'm more comfortable with having all of the build, options, etc. in one place in mill rather than npm 😅.

> So vite should allow us to have hot module reloading (ie. updating the page without refreshing), which I think will be the main benefit compared to the old build. It isn't working yet though.

The page refreshes are pretty quick, and we're now maintaining most of the important parts of the page state in local or session storage... partly because React has been resetting components to their initial states a bunch and I haven't totally figured out why. (Oops.) But actually, maintaining state between refreshes is convenient, especially if people get disconnected etc.. so I'm not sure if this is a dire need at the moment.

> I think I should be able to get it working from a single port with vite.

If you fiddle with it a bit and it seems like too much of a pain, I'm happy to just go at it and try out mill-bundler again. I think I can comfortably configure it for dev and prod.

> IntelliJ does not like this structure 😢

Oh no :( I've never tried IntelliJ with Scala so I haven't run into this issue before. Did you figure it out? Happy to find some kind of compromise. Based on the issues I've found reported online (eg [here](https://youtrack.jetbrains.com/issue/IDEABKL-6745#focus=streamItem-27-2672229.0-0)) seem to imply having multiple modules sharing source just doesn't work in IntelliJ — in which case I wonder how cross-platform projects work at all? Since we have different modules for JVM and JS.

**Comment by UFO-101** [comment]
> that should do incremental recompiles but issue is that re-linking isn't incremental

Oh okay. But are you saying that `mill -i debate.dev.serve --port 8080 --save save ` should not have been incredibly slow? Does using `-w` mean that re-linking isn't required because it's like the 'same' compilation or something?

(Will respond later to the rest)

**Comment by julianmichael** [comment]
It will be slow the first time since it has to do the whole build, but subsequent invocations should be much faster, since most of the time is spent on compiling and it should only need to recompile the files you changed. `-w` won't change this, it'll just make it re-run every time the source files change.

In the old build I had it set up so that `serve` depended on the `fastestOpt` target which linked the JS. I did this out of convenience, to run the server from clean with a single command and to pass the location of the linked JS file to the server. But for the dev loop it'll be faster to leave the server running and recompile/relink the JS only (like you did with the vite build), so we can leave it that way. Using `-w` when spinning up the server (eg `mill -w debate.dev.serve` or `mill -w debate.jvm.run`) won't actually do anything once the server is running — the `-w` flag will suspend and wait for source changes once the task finishes, but the server doesn't terminate unless we interrupt it. So we still need to manually restart the server when we make changes to the JVM code.

To be more specific on build times, for me on my M1 Mac Mini, it took about 1 minute to do a clean build, and then less than 10 seconds on subsequent invocations. Running it on my M2 Macbook Air, it gets noticeably slower if I am saving files a lot with `mill -w debate.js.publicDev` and constantly compiling, which overheats the machine. (A computer with a fan may fare better.)

One thing which might help regardless: right now, mill and metals are duplicating work and compiling everything twice. I asked in the gitter to see if we can get them to share compile output; not sure if the functionality is there.

**Comment by julianmichael** [comment]
Also, I might have spoken too confidently about re-linking not being incremental — there were times after I optimized the old build a bit that relinking seemed to go faster or not be required, but I don't totally understand when & why that was happening.

**Comment by julianmichael** [comment]
Aha — you can switch Metals from using bloop as its build server to using the Mill BSP. The command is `metals.bsp-switch` or may have a better name in your Metals extension... though maybe IntelliJ isn't using Metals, in which case there might be a different way. But you should be able to use the mill build server, which I think should reduce the duplicated work. Anecdotally things seem slightly faster to me now.

**Comment by UFO-101** [comment]
Hi sorry for the slow response.

Okay I'm still pretty confused about what (if anything) I was doing wrong with the old build, and how much slower or not it actually was. It seems like there were 3 things that could have made it slower:
 - Not using the -w flag (but it seems like once you've started the a new compilation this shouldn't make any difference)
 - Building both the jvm code and the js code
 - Not using `ModuleSplitStyle.SmallModulesFor(List("debate"))`. It seems like this was [commented out on the old build](https://github.com/julianmichael/debate/blob/d93715c52e2b2c8656064981e0e093756b0f0e39/build.sc). However, I just tested not using module splitting on the new build and it doesn't seem to make much difference to the speed.

Anyway if we're confident that the old build (ie. not using Vite) was not much slower then it seems like there is not much advantage in using Vite. Especially as the main benefits that I thought Vite provided (auto-prefixing CSS, hot module reloading) seem to not be as useful as I thought.

**Comment by julianmichael** [comment]
I see, sounds good. I will take a look at alternatives (particularly mill-bundler) and see if i can get a simple dev/prod setup again.

**Comment by julianmichael** [comment]
When I have it done I'll stick it in a branch and you can try it out and see if the build times / dev loop is noticeably worse

**Comment by julianmichael** [comment]
I need to get it up and running again with updates asap, so I just reverted to the old way of building. It's ultimately simpler to rely on ~20 lines of my own self-rolled code than have to deal with outside libraries with mysterious/questionable functionality.

And it still works without having to restart the server — as long as you're only updating the JS code, just run `mill debate.js.fastestOpt` again and refresh and I'm pretty sure that just works.
