### ISSUE TITLE
Debate auto-scheduler

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/debate#61]
We need to put together some functions for automatically scheduling debates.

A spec for a first function we need has been added in the [debate-scheduler](https://github.com/julianmichael/debate/tree/debate-scheduler) branch. See [here](https://github.com/julianmichael/debate/commit/4615e8bec81ded6da70a94e60f14443b7cbb5349).

After this we'll need a hook to use it in the interface.

**Comment by julianmichael** [comment]
Thoughts:
* There are a lot "costs" that we want to minimize — imbalance between debaters, judges judging the same story multiple times, etc.
* We will need to trade off these costs with each other, so it makes sense to explicitly compute them and combine them together into a single function on entire outputs (i.e., sets of assignments).

In theory we want to produce outputs which minimize this cost function... BUT, 
* This is probably intractable to compute, and
* We don't want the output to be perfectly predictable anyway, as people shouldn't be able to guess who they're debating / who's honest/dishonest based on previous history.

So instead of minimizing the cost function, we can use the cost function to define a distribution over outputs which favors lower-cost outputs, and sample from that distribution. Distributions defined in this way (monotonic with a cost function summed from several possibly-independent components) can be defined using [factor graphs](https://gtsam.org/2020/06/01/factor-graphs.html).

The simplest way to do this is probably via a softmax distribution based on the cost function (i.e., exponentiate and normalize), which corresponds to a [conditional random field](https://en.wikipedia.org/wiki/Conditional_random_field). If the nodes in the graph are independent, then sampling is easy because their values can be sampled in sequence. So you can cast the whole problem as one of sampling subparts from intermediate distributions based on cost functions.

For example:
* First, sample a split of debaters/judges
* Then, sample individual assignments in sequence

Or something like that.

**Comment by smithjessk** [comment]
Discussed with @julianmichael. 

We're going to punt on factor graphs for now. The scale of the problem [1] implies that it's tractable to solve it directly by enumerating all possible assignments and picking the one with the lowest cost. 

[1]: 10-15 debaters, scheduled in advance for 10-15 debates. (TBD what the # of stories is.)
