### ISSUE TITLE
Order completed debates by when they were assigned

### ISSUE THREAD

**Issue by sm11197** [julianmichael/debate#87]
Easier to track week by week accuracy

**Comment by sm11197** [comment]
Or I guess, by story first?

**Comment by julianmichael** [comment]
I'm thinking of a reorg of the lobby to group the debates by story + question anyway, particularly for when we have multiple debates per question. Week-by-week accuracy wouldn't be hard to put in an analytics pane (#73)

**Comment by julianmichael** [comment]
Actually though, I can do this reordering with a trivial change.. done
