### ISSUE TITLE
Remove last semester's results from leaderboard

### ISSUE THREAD

**Issue by sm11197** [julianmichael/debate#89]
**Purpose:** researchers are now unable to view the results of all debates. This means we can't easily track accuracy for the debates we currently care about

**Change wanted:** Might be something like moving certain JSON files to.. 
- Practice? You'll have to rename the mightiest qorn ones...
- New folder, practice-1? or something
Or tagging the debates or whatever was done so the offline debates don't show up on the leaderboard

TO REMOVE **Story-(ending numbers)**
mightiest-qorn-(0-2)
ambition-(0-5)
pied-piper-of-mars-(0-5)
jaywalker-(0-4)

**Comment by julianmichael** [comment]
I'm waiting to rejigger the leaderboard at the moment, until after I get the auto-scheduler set up and we can start running 2 debates per question. That'll give us a way of scoring debaters which is more appropriate for the leaderboard.

As for tracking overall accuracy and properties of the debates, that could make sense to add in the analytics pane later (#73)

**Comment by julianmichael** [comment]
But meh, this was a quick change so I just did it now anyway
