### ISSUE TITLE
Participant availability 

### ISSUE THREAD

**Issue by sm11197** [julianmichael/debate#90]
For automating scheduling, I'm assuming we'll need some way to mark availability per session

Since migrating feedback from Google Forms to the interface worked... I'm wondering if we could do that for Google Calendar. Participants seem to be better about marking things directly in the interface

**Comment by julianmichael** [comment]
Yes!
* For scheduling, what we'll have is a notion of the "relative workload" that each debater can take on. We can initialize this automatically based on each person's level of participation, and regulate it down and up as necessary.
* I am also setting up auto-scheduling to fill things in so the _currently active debates_ match someone's current workload. So if someone is falling behind, they won't get scheduled in new debates.

**Comment by julianmichael** [comment]
Seems like we went ahead without this and it's not clear if we'll want this for future experiments, gonna close it for now
